# Generated by Django 3.0.5 on 2020-04-29 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='choise',
        ),
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 4, 0, 1, 265411)),
        ),
    ]
