# Generated by Django 3.0.5 on 2020-05-10 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0003_auto_20200510_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loade',
            name='lodePowerValue',
        ),
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 10, 2, 59, 680668)),
        ),
    ]
