# Generated by Django 3.1.3 on 2021-03-27 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0004_auto_20200510_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loade',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='loadedetels',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lodelable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 19, 18, 48, 943878)),
        ),
        migrations.AlterUniqueTogether(
            name='profilepicture',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='loade',
            table='loade',
        ),
        migrations.AlterModelTable(
            name='loadedetels',
            table='loadeDetels',
        ),
        migrations.AlterModelTable(
            name='lodelable',
            table='lodeLable',
        ),
        migrations.AlterModelTable(
            name='profilepicture',
            table='profilePicture',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
