# Generated by Django 3.2.7 on 2022-05-10 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0008_auto_20210327_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 9, 58, 32, 181895)),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('discption', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.ImageField(upload_to='item/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ROOT.user')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
    ]
