# Generated by Django 3.2.7 on 2022-05-10 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0010_auto_20220510_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 27, 11, 404329)),
        ),
    ]
