# Generated by Django 3.2.7 on 2022-05-14 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0011_auto_20220510_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 19, 53, 40, 430178)),
        ),
        migrations.CreateModel(
            name='PascodeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valid', models.IntegerField(default=0)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ROOT.item')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ROOT.user')),
            ],
            options={
                'db_table': 'pascodeRequest',
                'managed': True,
            },
        ),
    ]
