# Generated by Django 3.2.7 on 2022-05-14 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROOT', '0012_auto_20220514_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedetels',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 21, 13, 45, 529515)),
        ),
        migrations.AlterField(
            model_name='pascoderequest',
            name='itemId',
            field=models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.DO_NOTHING, to='ROOT.item'),
        ),
        migrations.AlterField(
            model_name='pascoderequest',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='ROOT.user'),
        ),
    ]
